### ISSUE TITLE
error as below

### ISSUE THREAD

**Issue by sibjac** [Jagdish99Chandra/alice_blue_tradingbot#1]
I am getting below  error
Error in Hist_data:  Expecting value: line 1 column 1 (char 0)

**Comment by Jagdish99Chandra** [comment]
> I am getting below error Error in Hist_data: Expecting value: line 1 column 1 (char 0)
Use the updated code if it still not works for you than ===>
Connect with me on [99chandrajagdish@gamil.com](mailto:99chandrajagdish@gamil.com) from there i can assist you.

**Comment by sibjac** [comment]
getting this message when logged in
websocket run forever ended in exception, WebSocketApp.run_forever() got an unexpected keyword argument 'ping_payload'.

sorry for writing this here,   but not able to connect with [99chandrajagdish@gamil.com], it says could not find id

**Comment by Jagdish99Chandra** [comment]
> getting this message when logged in websocket run forever ended in exception, WebSocketApp.run_forever() got an unexpected keyword argument 'ping_payload'.
> 
> sorry for writing this here, but not able to connect with [[99chandrajagdish@gamil.com](mailto:99chandrajagdish@gamil.com)], it says could not find id

sorry for the miss-typed gmail its 99chandrajagdish@gmail.com you can msg here.

**Comment by sibjac** [comment]
error is :   

websocket run forever ended in exception, WebSocketApp.run_forever() got an unexpected keyword argument 'ping_payload'.

please look into it when you get time,  no luck connecting with 99chandrajagdish@gmail.com

**Comment by sibjac** [comment]
it is working now.  i have upgraded the websocket_client.  Thank you
